//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioLogin", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class UsuarioLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.aliasField, value) != true)) {
                    this.aliasField = value;
                    this.RaisePropertyChanged("alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISRV_Login")]
    public interface ISRV_Login {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRV_Login/Login", ReplyAction="http://tempuri.org/ISRV_Login/LoginResponse")]
        WEB.ServiceReference1.UsuarioLogin Login(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRV_Login/Login", ReplyAction="http://tempuri.org/ISRV_Login/LoginResponse")]
        System.Threading.Tasks.Task<WEB.ServiceReference1.UsuarioLogin> LoginAsync(string usuario, string clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISRV_LoginChannel : WEB.ServiceReference1.ISRV_Login, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRV_LoginClient : System.ServiceModel.ClientBase<WEB.ServiceReference1.ISRV_Login>, WEB.ServiceReference1.ISRV_Login {
        
        public SRV_LoginClient() {
        }
        
        public SRV_LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRV_LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRV_LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRV_LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB.ServiceReference1.UsuarioLogin Login(string usuario, string clave) {
            return base.Channel.Login(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<WEB.ServiceReference1.UsuarioLogin> LoginAsync(string usuario, string clave) {
            return base.Channel.LoginAsync(usuario, clave);
        }
    }
}
